version: "3.9"

services:
  polideportivo-mysql:
    image: mysql
    container_name: polideportivo-mysql
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: polideportivo
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./db-data:/var/lib/mysql


#mysql -u root -p (polideportivo)
